### PR TITLE
Modern look for the website

### PR DESCRIPTION
**Pull request by visortelle**
### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

Hi everyone!

I don't think anyone will argue, it’s important to have a fresh-looking website to attract new users.

I decided to try to refresh it a little bit.

Over the weekend I managed to make a home page. I think that I can finish other pages in 1-2 weeks, depending on my workload.

Current version: https://pulsar.apache.org/
**New version:** https://pulsar-site-three.vercel.app/

After the redesign, I plan to add a few more pages.

Should I continue?

### Before

Screenshot 2023-02-19 at 11 31 07 PM

### After

Screenshot 2023-02-19 at 11 34 18 PM

### CODE REVIEW

**Comment by Anonymitaet** [comment]
Hi @visortelle thank you very much for your awsome job! This is a great addition to the Pulsar website! 

Many users choose white background since it's more beautiful (modern and clear) and useful (increases readbility). Context see https://github.com/apache/pulsar/issues/15538#issuecomment-1125602899.

@emidio-cardeira is working on the visual designs for the Pulsar website, does this change LGTY?

---

While I find some issues as below.

### 1. Content is missing

https://pulsar-site-three.vercel.app/docs/next/
image

### 2. Content is inconsistent

2.1 https://pulsar-site-three.vercel.app/community/#section-welcome
image

Carousel is more efficient and funny than showing pic one by one.
image

2.2 Can we consolidate them into one table?
https://pulsar-site-three.vercel.app/community/#section-welcome
image
 
2.3 Same to
image

### 3. Content is out of order

3.1 All contents on https://pulsar-site-three.vercel.app/case-studies/ are disordered.
image

3.2 Same to
https://pulsar-site-three.vercel.app/resources/
image

3.3 Same to
https://pulsar-site-three.vercel.app/events/
image

**Comment by Anonymitaet** [comment]
### Request more review

@emidio-cardeira is working on the visual design

@asafm and @dave2wave are working on the copy

Does this change LGTY? Thank you!

FYI @@D-2-Ed @merlimat @jak78

**Comment by visortelle** [comment]
@Anonymitaet

I asked only about the home/index/root (`/`) page look.

Other pages just aren't re-implemented.

I don't know the history behind the previous redesign that was not so long time ago. I met many situations when people didn't want to consider changes for some reason.

Therefore I must be sure that the proposed changes most likely will be accepted before investing my time.

**Comment by asafm** [comment]
Hi @visortelle,
I truly agree with you, the Pulsar website doesn't reflect the awesomeness and how modern Pulsar is. This why @emidio-cardeira, and a few others, are working on a full revamp which will look absolutely stunning. We are currently preparing the PIP, which will show the screenshots of the design and motivation for each change.

**Comment by visortelle** [comment]
@asafm I'm glad to hear that work is being done in this direction.

A bit bad that I wasted my time on this. But I remembered how to deal with CSS. 😄

Can't wait to see the PIP.

**Comment by asafm** [comment]
@visortelle There is the unwritten open source rule: consult before investing large effort :) In Apache Pulsar, DEV mailing list would be the best place for it.

**Comment by tisonkun** [comment]
Closing as preferring another initiative.

@asafm @emidio-cardeira do you have an estimate for publishing the PIP? It's good for publicly review a common need instead of long-time in house designing - following the same rule that "consult before investing large effort", lol.

**Comment by asafm** [comment]
@tisonkun 1-2 weeks roughly. We are not publishing a real web-site, but screenshots, so we're not investing a huge effort, but the needed effort to get the actual design approved, and then we'll be able to continue with the large effort itself.

**Comment by visortelle** [comment]
@asafm sure I will ask before doing something next time.

My wrong assumption was that the previous redesign was not so long time ago, in May 2022. https://lists.apache.org/thread/7nx3rm3cmpbw0ws1b62k17935xgyw2tj
And it's unlikely there planned one more redesign in less than a year.

Anyway, the two days I spent aren't so much, and I have an idea of where I can reuse this code and text.

+1 for the @tisonkun's point.

**Comment by Anonymitaet** [comment]
@visortelle you efforts are not wasted because we can still apply it once the community agrees. I'll give my +1 on this beautiful and useful design.

**Comment by asafm** [comment]
@visortelle PIP released: https://github.com/apache/pulsar/issues/19611

**Pull request closed without merging**
