### PR TITLE
Update sql-rest-api.md

### PR DESCRIPTION
**Pull request by Samreay**
Fixing misplaces backtick

This PR fixes a typo

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by Anonymitaet — COMMENTED** [review]
Thanks for your contribution!

Does this change apply to other doc versions? If so, please update them all

**Comment by Samreay** [comment]
Nah, only the 3.0.x ones were wrong, the older docs are good

**Comment by Anonymitaet** [comment]
How about docs on master?

**Comment by Samreay** [comment]
Didn't even realise there was a non-versioned duplicate set. Have changed that file too.

**Review by tisonkun — APPROVED** [review]
Thank you!

**Pull request merged**
