### PR TITLE
[improve][doc] Optimize Admin API > Features > Functions

### PR DESCRIPTION
**Pull request by Anonymitaet**
## What issues does this PR solve?

There are some issues in the current [Admin API > Features > Functions](https://pulsar.apache.org/docs/next/admin-api-functions/) doc. I’ve summarized them with the corresponding solutions below.

Issues | Solutions
-- | --
Some operations are in chaotic order. | Categorize operations logically to match users' learning pace. <br><br>For example, classify operations based on the CRUD sequence.
Some docs are redundant and scattered. | Consolidate and optimize the explanations.
Some docs are wrongly placed. <br><br>For example, "Concept"-type docs are shown in Sub-features, while they should be located elsewhere in Pulsar docs. | Move and consolidate them to the correct place. 

### ✅ High-level structure changes

- 🍊Old structure
image

- 🍊New structure

🙌Final version
image

❌Deprecated version
image

## More context

This PR is a part of the "improving the DX and taking Pulsar API docs to the next level" project.

Related PRs:
- [[improve][doc] Relocate content in admin API overview](https://github.com/apache/pulsar/pull/18680)
- [[feat][doc] Add Pulsar API content](https://github.com/apache/pulsar/pull/19002)
- [[feat][doc] Add Use Cases Features, Tools to Pulsar admin API](https://github.com/apache/pulsar-site/pull/403)
- [[feat][doc] Add "Get Started" for API (Java + REST) and CLI (pulsar-admin)](https://github.com/apache/pulsar-site/pull/462)
- [[improve][doc] Optimize "Admin API > Features > Clusters" ](https://github.com/apache/pulsar-site/pull/490)
- [[improve][doc] Optimize "Admin API > Features > Brokers"](https://github.com/apache/pulsar-site/pull/493)

==================================

- [x] `doc` 

Ping @momo-jun @D-2-Ed to review, thank you!

### CODE REVIEW

**Comment by Anonymitaet** [comment]
The preview looks good:
image

**Comment by Anonymitaet** [comment]
Hi @freeznet Could you please review this PR from a technical perspective? Thank you!

**Review by momo-jun — APPROVED** [review]
Generally, it looks good to me.

Two suggestions:
1. Narrow down the hot link items to enhance the navigation readability by not showing trivial ones for either one instance or all instances (heading3). After clicking on the heading2, users can continue to select between two options.
2. Move "Restart" prior to "Delete". It has a closer sense to the Update or Del category, rather than the Create category.

**Comment by Anonymitaet** [comment]
@momo-jun thanks!

For 1: 
I prefer to keep it as it is since:
1) If not setting "instance" and "all instances" as headings, then there are no links for them, which makes sharing the link of a specific operation impossible.  
2) Previously, I tried to use multiple tabs for "instance" and "all instances" but failed. I guess it is due to Docusraus does not support "embed tabs" (so as [no relevant docs](https://docusaurus.io/docs/next/markdown-features/tabs)).

For 2:
I prefer to keep it as it is since "Restart" is more closely related to the "Create" operation rather than the "Update/Delete" operation because it "wakes up" a function from "sleep" or makes it "alive" from "dead", kind of "creating a life".

**Comment by Anonymitaet** [comment]
I've discussed the doc structure with @freeznet and adjusted it as shown in the "Final version" in this [PR description](https://github.com/apache/pulsar-site/pull/498#issue-1645351049).

Reason for this change:
- Devs get accustomed to this sequence of operations. It's natural and easy to use.
- Strictly speaking, some operations can not be categorized in "CRUD" logic.

**Comment by Anonymitaet** [comment]
Hi @freeznet 

I've adjusted the doc structure based on your guidance. The preview looks good. Can you review this PR? TIA!

image

**Review by freeznet — APPROVED** [review]

**Review by nlu90 — APPROVED** [review]

**Comment by Anonymitaet** [comment]
@freeznet @nlu90 thank you!

**Pull request merged**
