### PR TITLE
Add back charts/index.yaml

### PR DESCRIPTION
**Pull request by tisonkun**
This closes https://github.com/apache/pulsar/issues/17799.

### CODE REVIEW

**Comment by tisonkun** [comment]
Root cause: https://github.com/apache/pulsar-site/pull/222

**Comment by tisonkun** [comment]
cc @lhotari @urfreespace

**Comment by frankjkelly** [comment]
Any way we can get this merged ASAP it's blocking a lot of our Jenkins jobs?

**Review by codelipenghui — APPROVED** [review]

**Comment by tisonkun** [comment]
@frankjkelly merged. Although, it can take some time to deploy online. Typically in minutes.

**Comment by frankjkelly** [comment]
Awesome - thanks for the quick turn around - LGTM now

Here is the before and after
```
$ helm repo add apache https://pulsar.apache.org/charts
Error: looks like "https://pulsar.apache.org/charts" is not a valid chart repository or cannot be reached: failed to fetch https://pulsar.apache.org/charts/index.yaml : 404 Not Found
 $ helm repo add apache https://pulsar.apache.org/charts
"apache" has been added to your repositories
```

**Pull request merged**
