### PR TITLE
Update client-libraries-cluster-level-failover.md

### PR DESCRIPTION
**Pull request by visxu**
Fix issue: https://github.com/apache/pulsar/issues/23512

### ✅ Contribution Checklist

- [x] I read the [contribution guide](https://pulsar.apache.org/contribute/document-contribution/)
- [x] I updated the [versioned docs](https://pulsar.apache.org/contribute/document-contribution/#update-versioned-docs)

### CODE REVIEW

**Comment by visxu** [comment]
@crossoverJie Hi, Jie. Um... I'm not sure who could be invited to approve the PR, could you help on it? So appreciated.

**Comment by nodece** [comment]
@visxu Please update https://github.com/apache/pulsar-site/blob/main/docs/client-libraries-cluster-level-failover.md, which is the latest version.

**Comment by visxu** [comment]
> @visxu Please update https://github.com/apache/pulsar-site/blob/main/docs/client-libraries-cluster-level-failover.md, which is the latest version.

Sure, new PR: https://github.com/apache/pulsar-site/pull/969
I'll close the PR.

**Comment by nodece** [comment]
This PR is used for Pulsar 3.x, https://github.com/apache/pulsar-site/pull/969 is used for Pulsar 4.x.

**Pull request merged**
