### PR TITLE
[improve][doc] Implementing documentation for debugging Pulsar source code

### PR DESCRIPTION
**Pull request by ubo-dev**
This PR adds doc for #[21707](https://github.com/apache/pulsar/issues/21707)

This PR fixes #[21707](https://github.com/apache/pulsar/issues/21707)

- [X] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 

image
image
image

### CODE REVIEW

**Comment by lhotari** [comment]
The content is great! Thanks for the contribution! The only suggested improvement is to place the content in navigation where we have the IDE setup and development instructions. The main title could be about "Debugging Pulsar source code in IDE", etc. . @tisonkun could you help suggesting a good location for this great content that is included in this PR?

**Comment by ubo-dev** [comment]
> The content is great! Thanks for the contribution! The only suggested improvement is to place the content in navigation where we have the IDE setup and development instructions. The main title could be about "Debugging Pulsar source code in IDE", etc. . @tisonkun could you help suggesting a good location for this great content that is included in this PR?

Thanks a lot! I'll be waiting for the suggestion.

**Comment by lhotari** [comment]
> Thanks a lot! I'll be waiting for the suggestion.

It seems that the contribution guide's at https://pulsar.apache.org/contribute/ would be where to have the debugging instructions. Perhaps under the "Development" or "Getting Started" section in the navigation could be a good location.

**Comment by ubo-dev** [comment]
> > Thanks a lot! I'll be waiting for the suggestion.
> 
> It seems that the contribution guide's at https://pulsar.apache.org/contribute/ would be where to have the debugging instructions. Perhaps under the "Development" or "Getting Started" section in the navigation could be a good location.

Under the "Getting Started" section is looking good to me. I'll edit it now.

**Review by lhotari — APPROVED** [review]
Great job! LGTM

**Review by tisonkun — APPROVED** [review]

**Pull request merged**
