### PR TITLE
[fix] remove extra dot to fix render problem

### PR DESCRIPTION
**Pull request by labuladong**
This PR fixes https://github.com/apache/pulsar/issues/20470

Just a global replacement to fix this issue. Local preview:

image

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
Thank you!

**Comment by tisonkun** [comment]
As it touches a large range of versions, it may take a bit longer time to build. But let's wait a bit to ensure that we don't introduce new syntax error.

**Comment by tisonkun** [comment]
No. It touches only two versions. I'll merge this patch now.

@labuladong do you check that other old version won't be affected?

**Comment by labuladong** [comment]
Other older versions won't be affected, because the older versions don't have the `:::note` tab.

**Pull request merged**
