### PR TITLE
[fix][doc] Fix links to Broker Load Balancing Use Cases doc by renaming it.

### PR DESCRIPTION
**Pull request by ble**
This PR renames 2 copies of 1 doc, changing the end of it from `use-case.md` to `use-cases.md` to fix internal links.

I found that one link to that doc was broken (Check the 2nd link under the [Related topics heading linked here](https://pulsar.apache.org/docs/next/concepts-broker-load-balancing-concepts/#related-topics) and then confirmed that the file was currently named `...use-case.md` while all links to it point at `...use-cases.md`.

This PR fixes #21306
- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Comment by ble** [comment]
Quick integrity checking, just on the filesystem:
```
pulsar-site % # Let's search for all instances of 'broker-load-balancing-use-case' or 'broker-load-balancing-use-cases' in the docs:
pulsar-site % rg 'broker-load-balancing-use-cases?'versioned_docs/version-3.1.x/concepts-broker-load-balancing-overview.md
32:- To discover different usage scenarios, see [Broker load balancing | Use cases](./concepts-broker-load-balancing-use-cases.md).

versioned_docs/version-3.1.x/concepts-broker-load-balancing-quick-start.md
582:- To discover different usage scenarios, see [Broker load balancing | Use cases](./concepts-broker-load-balancing-use-cases.md).

versioned_docs/version-3.1.x/concepts-broker-load-balancing-benefits.md
45:- To discover different usage scenarios, see [Broker load balancing | Use cases](./concepts-broker-load-balancing-use-cases.md).

versioned_docs/version-3.1.x/concepts-broker-load-balancing-use-case.md
2:id: concepts-broker-load-balancing-use-cases

versioned_docs/version-3.1.x/concepts-broker-load-balancing-features.md
19:- To discover different usage scenarios, see [Broker load balancing | Use cases](./concepts-broker-load-balancing-use-cases.md).

versioned_docs/version-3.1.x/concepts-broker-load-balancing-concepts.md
559:- To discover different usage scenarios, see [Broker load balancing | Use cases](./concepts-broker-load-balancing-use-cases.md).

versioned_docs/version-3.1.x/concepts-broker-load-balancing-migration.md
162:- To discover different usage scenarios, see [Broker load balancing | Use cases](./concepts-broker-load-balancing-use-cases.md).

versioned_docs/version-3.1.x/concepts-broker-load-balancing-types.md
39:- To discover different usage scenarios, see [Broker load balancing | Use cases](./concepts-broker-load-balancing-use-cases.md).

sidebars.json
34:            "concepts-broker-load-balancing-use-cases",

docs/concepts-broker-load-balancing-migration.md
162:- To discover different usage scenarios, see [Broker load balancing | Use cases](./concepts-broker-load-balancing-use-cases.md).

docs/concepts-broker-load-balancing-features.md
19:- To discover different usage scenarios, see [Broker load balancing | Use cases](./concepts-broker-load-balancing-use-cases.md).

docs/concepts-broker-load-balancing-use-case.md
2:id: concepts-broker-load-balancing-use-cases

docs/concepts-broker-load-balancing-overview.md
32:- To discover different usage scenarios, see [Broker load balancing | Use cases](./concepts-broker-load-balancing-use-cases.md).

docs/concepts-broker-load-balancing-concepts.md
559:- To discover different usage scenarios, see [Broker load balancing | Use cases](./concepts-broker-load-balancing-use-cases.md).

docs/concepts-broker-load-balancing-quick-start.md
582:- To discover different usage scenarios, see [Broker load balancing | Use cases](./concepts-broker-load-balancing-use-cases.md).

docs/concepts-broker-load-balancing-benefits.md
45:- To discover different usage scenarios, see [Broker load balancing | Use cases](./concepts-broker-load-balancing-use-cases.md).

docs/concepts-broker-load-balancing-types.md
39:- To discover different usage scenarios, see [Broker load balancing | Use cases](./concepts-broker-load-balancing-use-cases.md).

versioned_sidebars/version-3.1.x-sidebars.json
34:            "concepts-broker-load-balancing-use-cases",
pulsar-site % # What do you know, in every instance it's 'use-cases', not 'use-case'.
```

```
# Now, is that the name of the file that we actually have?
pulsar-site % find . | rg 'broker-load-balancing-use-cases?'
./docs/concepts-broker-load-balancing-use-case.md
./versioned_docs/version-3.1.x/concepts-broker-load-balancing-use-case.md
% # No, all the files are named `use-case.md`.
```

**Comment by ble** [comment]
# Previewing docs on **main** branch:
## Hovering over one of these (broken) cross-document links:
image

## After navigating by that link:
image

# Previewing docs on **PR** branch:
## Hovering over one of these cross-document links:
image

## After navigating by that link:
image

**Comment by ble** [comment]
Docusaurus agrees that the links are not correct 🦖😊:
image

**Review by Technoboy- — APPROVED** [review]

**Comment by Technoboy-** [comment]
Thanks

**Pull request merged**
