### PR TITLE
Add the release note for Python client 3.0.0

### PR DESCRIPTION
**Pull request by BewareMyPower**
Preview

image

image

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]

**Comment by tisonkun** [comment]
Merging...

**Comment by tisonkun** [comment]
Oops..

Perhaps the release note can be revisioned by other developers. I should hold for a while...

But you can still make follow-ups. Sorry for rushing >_<

**Comment by BewareMyPower** [comment]
@tisonkun Actually I'm wondering if there is a way to synchronize the release note. Because the release note was just copied from the GitHub release page: https://github.com/apache/pulsar-client-python/releases/tag/v3.0.0

**Comment by tisonkun** [comment]
@BewareMyPower We can provide a tool to generate but never automation.

If you try to write an automation, how to periodically run and find diff is challenging. Or you can trigger from the release. And way, you can try to write it but I don't recommend.

**Pull request merged**
