### PR TITLE
Add Books page

### PR DESCRIPTION
**Pull request by visortelle**
This PR adds doc for #xyz

This PR fixes #xyz 

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

Demo: https://pulsar-site-git-books-and-videos-teal-tools.vercel.app/books/

Any suggestions on technology-neutral books? @tisonkun @asafm 

https://github.com/apache/pulsar-site/assets/9302460/c6a9c576-2d5f-422e-8f6e-33a464cd729b

### CODE REVIEW

**Comment by merlimat** [comment]
I would put books as part of "additional resources" rather than in the main documentation session

**Comment by david-streamlio** [comment]
LGTM

**Comment by visortelle** [comment]
@merlimat Hi! 👋

The current placement I took from the Kafka website:

Screenshot 2023-05-26 at 12 14 25 AM

I agree that it's probably not a good idea to have a dedicated page and navbar item for the books list. But I also wouldn't like to have them only in "additional resources".

A good book is that many people would like to know about when starting to learn new complex technology.

Ideally, I would like to see them both - at a very beginning of a learning journey, and in the "additional resources" section. Obviously makes it related to PIP-261 https://github.com/apache/pulsar/issues/19912

A good example here is Golang site. It has a dedicated `/learn` page with a list of suggested learning resources, grouped by format: tutorials, training, labs, and books.

https://go.dev/learn/

Screenshot 2023-05-26 at 12 43 31 AM
Screenshot 2023-05-26 at 12 11 17 AM

Scala also suggests books near the first steps:

https://docs.scala-lang.org/

Screenshot 2023-05-26 at 12 12 41 AM

Screenshot 2023-05-26 at 12 14 04 AM

---

Now we have a page that can be easily converted to React component and used in another place.
I'd want to create more pages with other content like a videos list, trainings list, etc.
The menu structure should be easy to adjust later.

---

The PR has been merged by the most popular Pulsar book author. Well, understandable. 😄 👍

**Comment by asafm** [comment]
@visortelle I prefer it to be located under Learn

**Comment by tisonkun** [comment]
In "Learn" > "Resource" we have a few entries for books already. I'm going to merge the Books into Resources.

Besides, information on the "Ecosystem" can be outdated and somehow inconsistent, I will go through that page as well.

**Comment by Anonymitaet** [comment]
@visortelle thanks for your contribution!

It makes more sense to locate "Books" under "Learn" because 
1) it's a way to learn Pulsar
2) many users get accustomed to finding books under the "Learn" rather than "Get Started"

Besides, the ["Resources" page](https://pulsar.apache.org/resources/) needs to be optimized since it contains both blogs and slides. While blogs have an independent category "Blog". They are overlapped somehow.



image

**Comment by visortelle** [comment]
@Anonymitaet I submitted a PR https://github.com/apache/pulsar-site/pull/606
Not sure about the dropdown items order.

**Pull request merged**
