### PR TITLE
[improve][doc] optimize old docs for broker load balancing

### PR DESCRIPTION
**Pull request by Anonymitaet**
## What change does this PR introduce?

This PR introduces the following changes (topics in the red box below)

- Removes old docs for broker load balancing, as we've added the new docs and published them on the Pulsar website (https://pulsar.apache.org/docs/next/concepts-broker-load-balancing-concepts/, https://pulsar.apache.org/docs/next/concepts-broker-load-balancing-types/)

- Brings "Anti-affinity namespaces" out of the broker load balancing docs and sets it as an independent section. This is a quick win as it is a copy from the existing doc https://pulsar.apache.org/docs/next/administration-load-balance/#distribute-anti-affinity-namespaces-across-failure-domains

image

## Doc development plan - Read before review

For the current doc of Broker Load Balancer, we want to tackle the following challenges:
- Create new documentation to cover all aspects of the feature (especially for the new extensible load balancer).
- Fill in any content gaps that may exist.
- Consolidate existing documentation into the new IA, as it is currently scattered and disorganized.
- Organize the documentation in a cohesive manner, ensuring it flows logically.

Consequently, we’ve created the following content development plans:
- [Broker Load Balancing | Information Architecture](https://xmind.works/share/dzbyKsnS)  
  This document presents a high-level architecture overview, including how we address content gaps and reconcile existing documentation.

- [Broker Load Balancing | Doc Outline](https://docs.google.com/document/d/1zshyn93XJp8Y-uvYLTnFCrcUWaHxeiTjPqdaUrR6zf0/edit#heading=h.6iz0wf853c5u)
  This document delves into the specifics of the content development plan, providing purpose and context for each section.

- [x] `doc` 

## Ackowledgements

@Demogorgon314 many thanks for your technical guidance and great support! 

cc @heesung-sn @@D-2-Ed

### CODE REVIEW

**Comment by Anonymitaet** [comment]
Preview looks good:

image

**Comment by Anonymitaet** [comment]
@Demogorgon314 @heesung-sn Could you please help review this PR? Thank you!

**Comment by heesung-sn** [comment]
I assume the content hasn't changed.

**Review by heesung-sn — APPROVED** [review]

**Comment by Anonymitaet** [comment]
@heesung-sn as explained in this PR description https://github.com/apache/pulsar-site/pull/663#issue-1832936126, "Anti-affinity namespaces" is a copy of the existing doc, while the docs of the removed file (https://github.com/apache/pulsar-site/pull/663/files#diff-4e5e00a17f8339a6681cbde816d8c72c42cedc430aac722c60b51f996fb42a84L262) have been covered in our new docs.

> I assume the content hasn't changed.

**Review by Demogorgon314 — APPROVED** [review]

**Pull request merged**
