### PR TITLE
Adjust the community page

### PR DESCRIPTION
**Pull request by visortelle**
### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

## Changes

- Adjusted styles.
- Added `<Section />` component that expects a title and contains the "wawy separator" by default.
- Added `<ContentCard />` and `<CardsLayout />` components to force styles consistency.
- Renamed Slack buttons as proposed here: https://github.com/apache/pulsar-site/pull/414#discussion_r1107878924
- Changed text of the Project Governance section.

### Before

hot-to-contribute-before

project-governance-before

### After

how-to-contribute-after

project-governance-after

### CODE REVIEW

**Comment by tisonkun** [comment]
@visortelle Thanks for your contribution! I'll review this patch by the end of tomorrow.

One suggestion is that you can checkout a new branch with a different name from `main` so that when I verify your patch locally there are no git related conflicts :)

**Review by tisonkun — CHANGES_REQUESTED** [review]
Thanks for your refactor and improvements @visortelle! This patch is in the right direction.

Comments here:

* May you move the components from under `src/pages` to `src/components`? All TSX files under `src/pages` can serve as a dedicated page; e.g., you can find http://localhost:3000/community/sections/discussions/DiscussionPlatforms a valid URL now after this patch, while it should not be an exported page.

The rest looks good.

**Comment by visortelle** [comment]
> Thanks for your refactor and improvements @visortelle! This patch is in the right direction.
> 
> Comments here:
> 
> * May you move the components from under `src/pages` to `src/components`? All TSX files under `src/pages` will serve as a dedicated page; e.g., you can find http://localhost:3000/community/sections/discussions/DiscussionPlatforms a valid URL now after this patch, while it should not be an exported page.
> 
> The rest looks good.

Fixed. Please check.

**Comment by tisonkun** [comment]
@visortelle Thanks for your update! I made a patch on your pull request at https://github.com/tealtools/pulsar-site/pull/1. Due to the duplicate branch name issue, I cannot just edit on your patch XD. Please take a look.

FWIW the branch name issue looks like:

```
╭─tison@mountarch in repo: pulsar-site on  tealtools/main:refs/pull/417/head via  v19.6.0 took 127ms
╰─λ git push
fatal: The upstream branch of your current branch does not match
the name of your current branch.  To push to the upstream branch
on the remote, use

git push origin HEAD:refs/pull/417/head

To push to the branch of the same name on the remote, use

git push origin HEAD

To choose either option permanently, see push.default in 'git help config'.

To avoid automatically configuring an upstream branch when its name
won't match the local branch, see option 'simple' of branch.autoSetupMerge
in 'git help config'.


╭─tison@mountarch in repo: pulsar-site on  tealtools/main:refs/pull/417/head via  v19.6.0 took 1ms
[🔴] × git push origin HEAD:refs/pull/417/head
Enumerating objects: 104, done.
Counting objects: 100% (104/104), done.
Delta compression using up to 32 threads
Compressing objects: 100% (84/84), done.
Writing objects: 100% (94/94), 19.80 KiB | 19.80 MiB/s, done.
Total 94 (delta 42), reused 9 (delta 3), pack-reused 0
remote: Resolving deltas: 100% (42/42), completed with 10 local objects.
To https://github.com/apache/pulsar-site.git
! [remote rejected]         HEAD -> refs/pull/417/head (deny updating a hidden ref)
error: failed to push some refs to 'https://github.com/apache/pulsar-site.git'
```

**Review by tisonkun — APPROVED** [review]
Merging...

**Comment by tisonkun** [comment]
@visortelle Thanks for your work!

**Pull request merged**
