### PR TITLE
Document connecting through a proxy

### PR DESCRIPTION
**Pull request by michaeljmarshall**
### Documentation

Adding docs for https://github.com/apache/pulsar/pull/19455

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Comment by michaeljmarshall** [comment]
Why are we checking the doc label here? Are almost all of these changes docs changes?

**Comment by tisonkun** [comment]
@michaeljmarshall here is the background: https://github.com/apache/pulsar/pull/19100#issuecomment-1367048663

... while I'm open to install or not. You may argue that since the source of docs moved out, most contributions to the main repo is not docs related.

**Comment by michaeljmarshall** [comment]
Thanks for that context @tisonkun!

**Review by Anonymitaet — APPROVED** [review]
Thanks for your contribution! Approved from a technical writing perspective.

**Pull request merged**
