### PR TITLE
Add "Suggest changes" and "Get support" links

### PR DESCRIPTION
**Pull request by visortelle**
A variation of this PR: https://github.com/apache/pulsar-site/pull/807

Screenshot 2024-03-01 at 12 49 23 PM

Suggest changes -> new GitHub issue with the "Document" template
Get Support -> new GitHub discussion in Q&A section

### CODE REVIEW

**Comment by jak78** [comment]
Thanks @visortelle 

Looks like there are now 2 different paths for people who want to contribute to the docs:
- the 'suggest changes' link that was just added
- the 'Edit' button at the bottom of each page

Moreover, the [homepage of the documentation mentions ](https://pulsar.apache.org/docs/3.2.x/#help-improve-these-documents)a 'landing page with instructions for requesting changes to posted documents.' However, upon clicking the Edit button, no such landing page with explanations is presented.

To streamline the process for those interested in contributing to the documentation, it might be beneficial to offer a single, straightforward path. Wa also need to eliminate references to this nonexistent landing page.

Thoughts?

**Comment by visortelle** [comment]
@jak78 I thought about it. Let me explain why I think the additional "Suggest changes" button makes sense.

The "Edit page" button is for someone able and willing to submit a PR. It may require 
 quite a lot of time.

The "Suggest changes" link is rather for someone who can explain what is wrong with the specific documentation page, but doesn't have enough knowledge or time to submit a PR. I think it would be good to have input from this part of the audience too.

Screenshot 2024-03-01 at 4 26 24 PM

**Comment by visortelle** [comment]
Regarding the non-existing “landing page with instructions for requesting changes to posted documents.”, probably it makes sense to remove this sentence.
I like how the "Edit" button works now - opens the page in the online text editor.

**Comment by jak78** [comment]
Thanks for your thoughts. That makes sense to me. Feel free to remove the reference to the non-existing landing page and explain the 2 distinct paths [here](https://pulsar.apache.org/docs/3.2.x/#help-improve-these-documents)

**Comment by visortelle** [comment]
@jak78 I'll make these fixes in a few days.

**Pull request merged**
