### PR TITLE
[fix][doc] make the navigation bar work better and uniform the font

### PR DESCRIPTION
**Pull request by zuobiao-zhou**
* Fixes https://github.com/apache/pulsar/issues/19948
* Fixes https://github.com/apache/pulsar/issues/19949

Using special markup in the titles of Markdown, such as HTML tags, is considered as part of the title. This can result in abnormal behavior of the navigation bar. This PR normalizes all the titles in version 2.11.x and resolves the mentioned issue.

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Comment by Anonymitaet** [comment]
Hi @tisonkun 
Could you please review this PR from a technical perspective? Thank you!

**Comment by Anonymitaet** [comment]
Hi @zuobiao-zhou thanks for your contribution! 

I've checked and found that these two issues (https://github.com/apache/pulsar/issues/19948 and https://github.com/apache/pulsar/issues/19949) not only exist in 2.11.x, but also in all versions. 

image

Would you like to fix them all after getting technical approval? Thank you!

**Comment by zuobiao-zhou** [comment]
Hi @Anonymitaet NP. I will fix them all after getting technical approval.

**Comment by zuobiao-zhou** [comment]
Hi, @tisonkun PTAL.
BTW, I just removed the special symbol in the title, (like ### `title` -> ### title or ### <em>title</em> -> ### title) and  I didn't change the content of the title.

**Review by tisonkun — CHANGES_REQUESTED** [review]
These files are generated from the [main repo](http://github.com/apache/pulsar).

You can find the related logic at https://github.com/apache/pulsar-site/blob/0d5d46d6b299380eab172757f74ea563e9295523/tools/pytools/bin/reference-doc-generator.py.

Please link to the PR in the main repo for changing the generating logic. Otherwise, changing only the generated files will be overwritten later.

**Review by tisonkun — COMMENTED** [review]
Manually updates released versions can be OK. But it's unstable for `next` or in case any maintained version generates new reference on patch release.

**Review by tisonkun — APPROVED** [review]
Thank you!

**Comment by tisonkun** [comment]
I suppose these are all reformatting to remove `em` and indent heading.

Merging...

**Comment by tisonkun** [comment]
Pending to trigger sync content once this commit are landed.

**Pull request merged**
