### PR TITLE
Add missing release notes and the version column

### PR DESCRIPTION
**Pull request by SignorMercurio**
This PR add missing release notes for legacy tag releases:

- 2.5.0
- 2.6.3
- 2.9.1

And also add a version column. Note that `$DATA/release-*.js` are removed as they should be generated during build.

image

### CODE REVIEW

**Comment by SignorMercurio** [comment]
@urfreespace @Anonymitaet

**Review by urfreespace — APPROVED** [review]

**Comment by tisonkun** [comment]
>  as they should be generated during build.

Please tell me how to. Currently, `./preview.sh` or `yarn run start` gives:

image

**Comment by urfreespace** [comment]
@SignorMercurio PTAL, suggest don't removing this files; just overwrite these files when building

**Comment by tisonkun** [comment]
Or you should integrate the automation clearly. Even from this PR, I don't know how to trigger the generate process - then the automation hurts understandability and debuggability.

**Comment by tisonkun** [comment]
I think it may be by running `./tools/release-json-gen.sh` but the relative paths don't work locally.

**Comment by tisonkun** [comment]
I understood it and succesfully preview. But it should be more intuitive and need no debug. Otherwise any contributor or even the reviewers don't spend time to understand how to troubleshooting it.

**Comment by SignorMercurio** [comment]
I see, maybe we should add these files back?

**Comment by tisonkun** [comment]
You can propose a patch and I'm glad to review it.

There's no a single word to resolve all this kind of issue but keep in mind that scripts and relative paths are already brittle, try to make it modular and try to ensure that contributors can preview with one command in a brand new environment.

**Comment by tisonkun** [comment]
```
Error:  Client bundle compiled with errors therefore further build is impossible.


Module not found: Error: Can't resolve '../data/release-pulsar.js' in '/pulsar/site2/website-next/release-notes'
Module not found: Error: Can't resolve '../data/release-java.js' in '/pulsar/site2/website-next/release-notes'
Module not found: Error: Can't resolve '../data/release-python.js' in '/pulsar/site2/website-next/release-notes'
Module not found: Error: Can't resolve '../data/release-cpp.js' in '/pulsar/site2/website-next/release-notes'
Module not found: Error: Can't resolve '../data/release-ws.js' in '/pulsar/site2/website-next/release-notes'
Module not found: Error: Can't resolve '../data/release-go.js' in '/pulsar/site2/website-next/release-notes'
Module not found: Error: Can't resolve '../data/release-node.js' in '/pulsar/site2/website-next/release-notes'
Module not found: Error: Can't resolve '../data/release-cs.js' in '/pulsar/site2/website-next/release-notes'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Build actually failed on this change.

**Comment by urfreespace** [comment]
@SignorMercurio could you PTAL? thanks

**Comment by SignorMercurio** [comment]
Yes, please checkout #247. @tisonkun @urfreespace

**Pull request merged**
