### PR TITLE
Lift site folder to the top level

### PR DESCRIPTION
**Pull request by tisonkun**
This closes https://github.com/apache/pulsar/issues/19090.

Modification:

* Lift files from `site2/website-next` to the root path.
* Corresponding update references.

### CODE REVIEW

**Comment by tisonkun** [comment]
As long as all CI tasks works, this change only affects the process to preview from the main repo.

From [the mailing list discussion](https://lists.apache.org/thread/89wl112cflvtoyfg3l7kglr1dozsljm9), we have a lazy consensus on this change is acceptable.

**Comment by tisonkun** [comment]
As long as all CI tasks works, this change only affects the process to preview from the main repo.

From [the mailing list discussion](https://lists.apache.org/thread/89wl112cflvtoyfg3l7kglr1dozsljm9), we have a lazy consensus on this change is acceptable.

**Comment by tisonkun** [comment]
To avoid conflicts from incoming content sync, we may have an in-time review on this patch.

**Comment by tisonkun** [comment]
To avoid conflicts from incoming content sync, we may have an in-time review on this patch.

**Comment by tisonkun** [comment]
Locally verified the build stage.

**Comment by tisonkun** [comment]
Verify publish logic at https://github.com/tisonkun/pulsar-site/actions/runs/3797492287/jobs/6458482393

View: https://github.com/tisonkun/pulsar-site/tree/asf-site-next

**Review by urfreespace — APPROVED** [review]
LGTM

**Comment by tisonkun** [comment]
Merging...

**Pull request merged**
