### PR TITLE
Security policy

### PR DESCRIPTION
**Pull request by tisonkun**
* This supersedes https://github.com/apache/pulsar-site/pull/21.
* This closes https://github.com/apache/pulsar/issues/18103.

### CODE REVIEW

**Comment by tisonkun** [comment]
Redirections verified locally:

```
cd site2/website-next
./preview.sh 2.10.x
docker-compose up
# open http://localhost/docs/security-policy-and-supported-versions
```

**Comment by tisonkun** [comment]
Merging...

FWIW this follows the pattern https://flink.apache.org/security.html.

We may later review that navbar to add a link to this page and improve its visibility.

**Comment by tisonkun** [comment]
To unblock https://github.com/apache/pulsar/issues/19090

**Comment by michaeljmarshall** [comment]
Thank you for pushing this initiative along, @tisonkun!

**Comment by michaeljmarshall** [comment]
@tisonkun - one question is what points to https://pulsar.apache.org/security/? I am not finding a reference on https://pulsar.apache.org/, maybe I am missing it.

**Comment by tisonkun** [comment]
@michaeljmarshall There's currently no and it was absent previously also.

For this point, I also think that the visibility of use cases and ecosystem deserves a higher level, as well as the security page. Thus, we may do some refactoring on the navbar. But I don't find time to give a proposal yet.

**Comment by michaeljmarshall** [comment]
Sounds good. The previous location wasn't ideal either, since it was in the versioned docs section. Do we have an issue to track the larger refactoring?

**Comment by tisonkun** [comment]
@michaeljmarshall Not yet. My thoughts are a bit scattered now. Perhaps I can spend some time after https://github.com/apache/pulsar/issues/19064 delivered. But you're welcome to list out your thoughts :)

**Comment by michaeljmarshall** [comment]
I added a bullet to https://github.com/apache/pulsar/issues/19064. Hopefully that's okay.

**Comment by tisonkun** [comment]
That should be fine, lol.

**Pull request merged**
