### PR TITLE
Fix inaccurate community info

### PR DESCRIPTION
**Pull request by SignorMercurio**
Fix apache/pulsar#15686.

Sorted based on `apacheId`. 

Reference: 
- https://apache-pulsar.slack.com/archives/C02Q4JLUB38/p1650931270994189
- https://people.apache.org/phonebook.html

### CODE REVIEW

**Review by michaeljmarshall — APPROVED** [review]
LGTM. I did not completely verify the accuracy of the list, but I quickly looked through it and it seems complete.

@SignorMercurio - how did you generate this list? Was it manual or do you have a script to get it from the phonebook?

**Comment by SignorMercurio** [comment]
@michaeljmarshall It's generated manually and double-checked with searching. It might also be possible to crawl the phonebook website and update this list.

**Review by Anonymitaet — CHANGES_REQUESTED** [review]
Thanks for your contribution!

Please do not merge this PR. I'll ask the community whether to show company info or not.

**Comment by SignorMercurio** [comment]
> I'll ask the community whether to show company info or not.

I think the phonebook page does not contain the information about committers' companies, so newly added committers do not have the `org` field.

**Comment by SignorMercurio** [comment]
Screenshot:

image

**Review by Anonymitaet — APPROVED** [review]

**Comment by Anonymitaet** [comment]
@urfreespace 
could you please review this PR from the technical perspective? Thank you!

**Review by urfreespace — APPROVED** [review]

**Comment by urfreespace** [comment]
> @urfreespace could you please review this PR from the technical perspective? Thank you!

LGTM

**Pull request merged**
