### PR TITLE
Fix release table versioning and style issues

### PR DESCRIPTION
**Pull request by SignorMercurio**
@urfreespace @Anonymitaet PTAL.

image

### CODE REVIEW

**Comment by tisonkun** [comment]
Hi @SignorMercurio! Is there any background about this patch? What problem does it want to fix now?

**Review by urfreespace — APPROVED** [review]

**Comment by urfreespace** [comment]
> Hi @SignorMercurio! Is there any background about this patch? What problem does it want to fix now?

it's while background before

image

**Comment by SignorMercurio** [comment]
@tisonkun Hi, the context is in a slack DM group with the two reviewer. The problems fixed are:

1. Replace the patch number with `x` for all versions above 2.8.
2. Remove releases that does not have a release note, or belongs to "Previous Releases".
3. Use transparent background that changes with day/night mode, instead of the white background.
4. Adjust table style as there are previously some unexpected styles.
5. Create component in `site2/website-next/src/components` and import it in `site2/website-next/release-notes/all.md` for better maintainability.

**Comment by tisonkun** [comment]
Thanks for your information! DMs are OK for quickly syncing up. But I'd suggest trying to bring more context when you start a process in the community instead of letting other participants to guess :)

**Pull request merged**
