### PR TITLE
Add a page about the contents of the Matrix form

### PR DESCRIPTION
**Pull request by zeo1995**

### CODE REVIEW

**Comment by tuteng** [comment]
@momo-jun PTAL

**Comment by tisonkun** [comment]
Cross referred to https://github.com/apache/pulsar/issues/17098.

**Comment by momo-jun** [comment]
Hi @zeo1995 can you pls rebase the master? This branch has conflicts with the latest updates and also better sync with a lot of recent updates. I wonder whether it's the cause of the local preview failure.

**Comment by tisonkun** [comment]
This can be superseded by #513.

**Pull request closed without merging**
