### PR TITLE
HomePage - Make the blurry part not be cut, but slowly become blurry as user scrolls to make it a smooth transition.

### PR DESCRIPTION
**Pull request by visortelle**
This PR adds doc for #xyz

This PR fixes #xyz 

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

Live demo: https://pulsar-site-pip-249-git-blur-transition-teal-tools.vercel.app/
Feature request: https://apache-pulsar.slack.com/archives/C04UXRZSMHV/p1686493144908659

https://github.com/apache/pulsar-site/assets/9302460/40c8d02b-5809-4e16-bcf2-f375c74f4a10

My only concern for such animations is performance on some devices, especially on mobile.

Please thumb up 👍 if it performs smoothly on your device.
Thumb down 👎 if not.

### CODE REVIEW

**Comment by jak78** [comment]
It performs smoothly on my 6-years-old phone.

**Comment by jak78** [comment]
Sorry, it was on a 3-year-old phone.
On a  6-year-old iPad, it does not perform great. But there are no rendering issues. And you can scroll down and use the landing page anyway.

**Review by tisonkun — APPROVED** [review]
LGTM. Thank you!

**Comment by tisonkun** [comment]
I'll merge this patch tomorror if there is no more argument.

**Comment by tisonkun** [comment]
Merging...

Thanks for your contribution @visortelle!

**Comment by asafm** [comment]
@visortelle said he will try a few tricks to make it smooth on iPhone/iPad

**Pull request merged**
