### PR TITLE
Fix set-persistent admin doc

### PR DESCRIPTION
**Pull request by tisonkun**
This supersedes https://github.com/apache/pulsar/pull/19001.

### Documentation

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@tjiuming PTAL, thanks!

**Comment by tisonkun** [comment]
One important issue that what versions are affected. From https://github.com/apache/pulsar/pull/18999 I can see only the NEXT version (3.0.0) is affected. Please confirm.

**Comment by tisonkun** [comment]
@Anonymitaet Thanks for your information.

Let's think of the change: the change commit to doc site will be published immediately, while the patch release will be out weeks or months later. It may not be a good idea to include changes to those versions now, but it helps we share information here.

**Comment by Anonymitaet** [comment]
We can tag this PR with the same labels and add docs to 2.9.x, 2.10.x, 2.11.x after those versions are released.

**Comment by tjiuming** [comment]
The code PR tagged with 2.9 2.10 2.11, I think keep align with it will be fine

**Comment by tisonkun** [comment]
Updated. Merging...

**Pull request merged**
