### PR TITLE
fix no stars

### PR DESCRIPTION
**Pull request by zrsaber**
Complete five（Show GitHub Star NO） from https://github.com/apache/pulsar/issues/15550 
image

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@urfreespace can you help review?

**Comment by Anonymitaet** [comment]
@zrsaber can we keep the GitHub icon as shown in the issue?
image

**Comment by zrsaber** [comment]
> @zrsaber can we keep the GitHub icon as shown in the issue? image

This is ok, but it will cause the icon to be small, like this, is this ok?
image

**Comment by zrsaber** [comment]
@[Anonymitaet](https://github.com/Anonymitaet)This is ok, but it will cause the icon to be small, like this, is this ok?
image

**Comment by Anonymitaet** [comment]
@zrsaber can we just keep the icon and NO. as exactly shown in the image? (leave `GitHub` out)
image

**Comment by zrsaber** [comment]
[Anonymitaet](https://github.com/Anonymitaet)This is ok,like this:
image

**Comment by Anonymitaet** [comment]
@zrsaber yes, I'm fine with this design.

> @Anonymitaet This is ok,like this: image

**Comment by zrsaber** [comment]
> @zrsaber yes, I'm fine with this design.
> 
> > @Anonymitaet This is ok,like this: image

@Anonymitaet ok, I have changed, like this:
image

**Comment by Anonymitaet** [comment]
LGTM. @urfreespace thoughts?

**Review by urfreespace — APPROVED** [review]

**Comment by urfreespace** [comment]
LGTM, thanks @zrsaber

**Pull request merged**
