### PR TITLE
[feature][doc] Apply the new REST API topic to versioned docs

### PR DESCRIPTION
**Pull request by momo-jun**
## Motivation

Apply the newly added REST API topic to all versioned docs.

## Modifications

1. Add the .md file to versioned docs.
2. Modify the sidebars.json files versioned docs.

### CODE REVIEW

**Comment by momo-jun** [comment]
@urfreespace @Anonymitaet can you pls review this PR? Thank you.

**Comment by Anonymitaet** [comment]
@momo-jun why not update docs earlier than 2.7.2? Don't we need to update docs for all versions otherwise users do not have restapi doc entrance?

**Comment by momo-jun** [comment]
> @momo-jun why not update docs earlier than 2.7.2? Don't we need to update docs for all versions otherwise users do not have restapi doc entrance?

I understand the maintenance rule is that only the versioned docs released in the last year are maintained and updated. Is it correct?

**Comment by Anonymitaet** [comment]
@momo-jun this doc update is different from other normal doc updates. 
We've removed "REST API" from top navigation, so users do not have a entrance to this doc
image
Now we need to add “REST API entrance" to every doc version, correct?

**Comment by momo-jun** [comment]
@Anonymitaet OK. I will do that for all versions.

**Comment by Anonymitaet** [comment]
@momo-jun have you checked the preview for all versions on your local machine?

**Comment by momo-jun** [comment]
@Anonymitaet Thanks for your reminder. I only previewed the latest version several days ago. 
Just figured out how to preview versioned ones with the help from @urfreespace. Now it's clear and done.

**Review by Anonymitaet — APPROVED** [review]

**Pull request merged**
