### PR TITLE
build: add containerized building 

### PR DESCRIPTION
**Pull request by tisonkun**
This PR fixes https://github.com/apache/pulsar/issues/20272

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

cc @visortelle @asafm welcome to test in your env:

```
docker-compose up
```

... should simply work and you can browse at http://localhost:3000/

### CODE REVIEW

**Comment by tisonkun** [comment]
Still, we need `.build-versions.json ` to specify build versions. I'm preparing a patch to use environment variable so that we can easily integrate it in the containerized building process.

**Comment by visortelle** [comment]
Confirm, it works.

**Comment by visortelle** [comment]
Maybe it has sense to **full build process** to Docker?

Let's say, I have such a problem in Python script that runs `yarn install`:

Screenshot 2023-05-15 at 2 18 56 PM

https://github.com/apache/pulsar-site/actions/runs/4979344185/jobs/8911494860

I'm not sure how I can debug it locally. The current Docker setup doesn't have any mention of Python, poetry package manager, etc.

**Comment by tisonkun** [comment]
@visortelle For the specific issue, maybe try out `yarn install` to see if any errors?

There are too much legacy scripts logic that need some time to migrate..

**Comment by tisonkun** [comment]
Let's discuss in your fork. It's unrelated to this PR or the upstream code.

Basically, you need to run `yarn install` before any other command. It looks like your run `node scripts/replace.js` before `yarn install` - the script is another tech debt.

**Comment by tisonkun** [comment]
I'll merge this patch first. Further improvement can be done later. I'll try to directly push some fix on the PIP-249 branch.

**Comment by asafm** [comment]
Works great!
Thanks!

**Pull request merged**
