### PR TITLE
Release Pulsar 3.1.2

### PR DESCRIPTION
**Pull request by AnonHxy**
Preview

image
image

```
- [x] `doc` <!-- Your PR contains doc changes -->
- [ ] `doc-required` <!-- Your PR changes impact docs and you will update later -->
- [ ] `doc-not-needed` <!-- Your PR changes do not impact docs -->
- [ ] `doc-complete` <!-- Docs have been already added -->
```

### CODE REVIEW

**Comment by AnonHxy** [comment]
@tisonkun @momo-jun @Technoboy-  PTAL

**Review by tisonkun — APPROVED** [review]
Thank you!

**Review by shibd — COMMENTED** [review]
@AnonHxy need to add version to https://github.com/apache/pulsar-site/blob/54092917a1389dc461b761a380d2de3f02663efa/releases.json#L17

**Comment by AnonHxy** [comment]
> @AnonHxy need to add version to https://github.com/apache/pulsar-site/blob/main/releases.json

Fixed. Thanks  @shibd

**Review by shibd — APPROVED** [review]

**Pull request merged**
