### PR TITLE
Fix reference page 404 issue

### PR DESCRIPTION
**Pull request by SignorMercurio**
Fix apache/pulsar#17996.

Also change versions like `2.6.0` to `2.6.x`, etc. (See #214)

### CODE REVIEW

**Comment by tisonkun** [comment]
@SignorMercurio how can I verify this change locally?

**Comment by SignorMercurio** [comment]
@tisonkun Simply go to `docsify` directory and run `docsify serve`.

**Comment by tisonkun** [comment]
@SignorMercurio this command verifies only the docsify site itself. How can I ensure that it's properly integrated with the Pulsar site? Said you state that 404 issues are resolved, it's actually about the integration instead of docsify standalone.

**Comment by SignorMercurio** [comment]
@tisonkun I haven't figured out an elegant way to do this, but you may try start a local HTTP server like this:

1. Create a temporary directory `website`:

```shell
$ mkdir /tmp/website
```

2. Copy the `docsify` directory to `website`:

```shell
$ cd site2/website-next
$ cp -r docsify /tmp/website/reference
```

3. Start a local HTTP server under `website`:

```shell
$ python3 -m http.server
```

4. Access http://localhost:8000/reference and you should see the new reference page.

**Comment by tisonkun** [comment]
@SignorMercurio This still tests only the docsify site instead of the integration with Pulsar website - you don't start a local server serving the doc site. And what is to be tested is jumping from the doc site to the reference pages correctly.

**Comment by tisonkun** [comment]
image

Still not found. I think when you're running `docsify serve`, it runs a new server serving the source files, while serves them as static file, markdown files and other meta files aren't recognized anymore.

**Comment by tisonkun** [comment]
Verified locally. Although not a fully integration, we can give it a try.

**Comment by tisonkun** [comment]
image

* http://localhost:8000/reference/#/latest/pulsar-admin/broker-stats

There're other 404 pages, please check whether they're generated on the fly?

**Comment by tisonkun** [comment]
Found:

```bash
# Generate document for command line tools.
"$TOOLS_DIR"/pulsar-admin-doc-gen.sh "$WEBSITE_DIR" "$VERSION"
"$TOOLS_DIR"/pulsar-client-doc-gen.sh "$WEBSITE_DIR" "$VERSION"
"$TOOLS_DIR"/pulsar-perf-doc-gen.sh "$WEBSITE_DIR" "$VERSION"
"$TOOLS_DIR"/pulsar-doc-gen.sh "$WEBSITE_DIR" "$VERSION"
"$TOOLS_DIR"/pulsar-config-doc-gen.sh "$WEBSITE_DIR" "$VERSION"
cd "$WEBSITE_DIR"
```

**Review by tisonkun — APPROVED** [review]

**Review by urfreespace — APPROVED** [review]

**Comment by SignorMercurio** [comment]
> There're other 404 pages, please check whether they're generated on the fly?

Yes, they are.

**Pull request merged**
