### PR TITLE
Suggest pulsar-admin-client

### PR DESCRIPTION
**Pull request by visortelle**

### CODE REVIEW

**Comment by urfreespace** [comment]
Thanks for @visortelle, but in fact, you need to modify the docs from the `pulsar` repo, https://github.com/apache/pulsar/blob/master/site2/website/versioned_docs/version-2.9.2/client-libraries-node.md, and the sync script will auto synchronous the docs change to `pulsar-site` repo from `pulsar` repo. cc @Anonymitaet

**Review by urfreespace — COMMENTED** [review]
Thanks for @visortelle, but in fact, you need to modify the docs from the `pulsar` repo, https://github.com/apache/pulsar/blob/master/site2/website/versioned_docs/version-2.9.2/client-libraries-node.md, and the sync script will auto synchronous the docs change to `pulsar-site` repo from `pulsar` repo. cc @Anonymitaet

**Comment by visortelle** [comment]
Done. https://github.com/apache/pulsar/pull/15839

**Comment by Anonymitaet** [comment]
@urfreespace @visortelle thanks, commented in new PR.

**Pull request closed without merging**
