### PR TITLE
[feat] add social card for render

### PR DESCRIPTION
**Pull request by tisonkun**
This PR fixes https://github.com/apache/pulsar/issues/21478

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Comment by visortelle** [comment]
The image background probably should filled with some color.
Otherwise, white text will be invisible on a white background.

Examples:
- https://assets-global.website-files.com/638a1dc72083d166ed6e3d76/63ad9cce111f58c7b64b646f_og-streamnative.webp
- https://cdn.confluent.io/wp-content/uploads/seo-logo-meadow.png

**Comment by visortelle** [comment]
https://socialsharepreview.com/?url=https://pulsar.apache.org

**Comment by tisonkun** [comment]
Yep. I try to use a different image - https://github.com/apache/pulsar-site/commit/ed1ebc18d089b083d7edb6f8dcfdf1053675b9fb

Now there is an image. But it may not be optimal for display.. Perhaps we need a resize?

image

**Comment by visortelle** [comment]
@tisonkun See https://github.com/apache/pulsar-site/pull/725

**Pull request merged**
