### PR TITLE
Update client-libraries-cluster-level-failover.md

### PR DESCRIPTION
**Pull request by visxu**
Fix issue: apache/pulsar#23512

### ✅ Contribution Checklist

- [x] I read the [contribution guide](https://pulsar.apache.org/contribute/document-contribution/)
- [x] I updated the [versioned docs](https://pulsar.apache.org/contribute/document-contribution/#update-versioned-docs)

### CODE REVIEW

**Comment by visxu** [comment]
@nodece Please help review the PR, thanks.

**Comment by lhotari** [comment]
@nodece When documentation changes apply to existing [supported versions](https://pulsar.apache.org/contribute/release-policy/#supported-versions), the versioned documentation in the versioned_docs directory should also be updated with the change. That was missed in this PR.
In the future, we could make it easier by providing a script in the pulsar-site repository that applies the changes made to docs folder to the versioned_docs of the supported versions. I have [some personal scripts for handling this](https://github.com/lhotari/pulsar-contributor-toolbox/blob/4d4d51c1b11103b35fc18eb9393db1819a4b585e/functions/pulsar-contributor-toolbox-functions.sh#L1947-L1990), but something similar could be part of pulsar-site repository and our instructions.

**Comment by nodece** [comment]
https://github.com/apache/pulsar-site/pull/968 is applied to the 3.0.x. If we can provide a script to cherry-pick this RP to the existing supported versions, it is awesome.

**Comment by lhotari** [comment]
> #968 is applied to the 3.0.x. If we can provide a script to cherry-pick this RP to the existing supported versions, it is awesome.

@nodece I have added the script in #972

**Pull request merged**
